service: email-api

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 256
  timeout: 30
  environment:
    STAGE: ${self:provider.stage}
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    EMAIL_HOST: ${env:EMAIL_HOST}
    EMAIL_PORT: ${env:EMAIL_PORT}

functions:

  serveHome:
    handler: src/handlers/webHandler.serveHome
    description: Serve HTML frontend
    events:
      - httpApi:
          path: /
          method: get

  sendEmail:
    handler: src/handlers/emailHandler.sendEmail
    description: Send email via REST API
    events:
      - http:
          path: send-email
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
